### ISSUE TITLE
Errors with pred_pssm.py

### ISSUE THREAD

**Issue by mohassan12** [sysu-yanglab/SPIDER2#3]
Getting the following error in pred_pssm.py
Traceback (most recent call last):
  File "../misc/pred_pssm.py", line 253, in <module>
    main([list_nn,ball], x, 'spd')
  File "../misc/pred_pssm.py", line 205, in main
    pred1(list_params, aa, pssm, outfile0)
  File "../misc/pred_pssm.py", line 217, in pred1
    res1 = run_iter(dict_nn, input_feature, aa, ofile)
  File "../misc/pred_pssm.py", line 158, in run_iter
    nn = dict_nn[x]
  File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/usr/lib64/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

**Comment by miss77jun** [comment]
pred_pssm.py L140 should be modified to 
```
return numpy.load(nn_filename, allow_pickle=True)
```
